name: GitHub Actions Test

on: [push]

jobs:
  testJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hi! I'm running because of a ${{ github.event_name }} event."
      - run: echo "Checking out the repository from ${{ github.repository }}."
      - name: Clone repository code
        uses: actions/checkout@v4
      - run: echo "Repository cloned, I think I'm ready. The files look like this:"
      - name: List files
        run: |
          ls "${{ github.workspace }}"
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: Install Azure ML CLI v2
        run: az extension add -n ml -y
      - name: Submit Azure ML job
        run: az ml job create --file job.yaml --resource-group practice1 --workspace-name practice1
